### ISSUE TITLE
The app is not finished

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NDC_OG#2]
Controls and features of the app:
- [x] link the electrification option to the map (solved in #3)
- [x] highlight the countries of the study on the world map (solved in #4)
- [x] define the visible controls for each scenarios
- [x] define the tier level control
- [x] implement the tier level control so that it makes sense (solved in #25)
- [x] add a fourth scenario which is se4all with variable inputs (all the others don't have controls): se4all-flex (solved in #7, 4ad3c35cdd1a5e1c4c7d6ff0db505f7f0d971864)

Results :
- [x] related / avoided GHG emissions (solved in #9)
- [x] initial investments for SHS, MG (solved in #9)
- [x] link the piechart to the study results (solved in #4)
- [x] add scatter points on the map (solved in #22, not merged yet as I am not sure we want it)
- [x] add aggregate tickbox (7c5e07d53ea6779c46349ad4c28061ecb1ddbb31)
- [x] aggregate the results by section (7c5e07d53ea6779c46349ad4c28061ecb1ddbb31)
- [x] add graphs in the results section (baec29dfae9ddbccc9bdde3d7bf677ff123c2889)
- [x] add the cumulative analysis
- [x] make a table with POPULATION NEWLY ELECTRIFIED in 2030, capacity, investment costs case 1 and 2. (21f0836f2608d964b125f9048069dc08d5723d07)
- [x] make a table with GHG 2017, 2030 and the cumul from 2017-2030 with a row consisting of the saved emission in contrast to using Bau scenario (21f0836f2608d964b125f9048069dc08d5723d07)

App design :
- [x] write general description of the app (bb2a8d00551007b53bb6f8f6c7f37d0f9cb5ca94)
- [x] write description of the scenarios within the app (bb2a8d00551007b53bb6f8f6c7f37d0f9cb5ca94)
- [x] write description of the electrification options. (91648828528bb3efca109747068a27525066a6b5)
- [x] format the dash_table.DataTables so they look nice (f1e762a1f1b0c2f48cd77cb507c57e1bc531d789)
- [x] format the dcc.Graph
- [x] apply styling (this has to be done with Bryan)

App deployment :  
- [ ] choose between django, heroku or dokker

Options :
- [ ] add investment cost control
- [ ] save the data in the case of se4all-flex
- [ ] be able to reset the data of se4all-flex
- [ ] be able to load csv files for initial data from the app
- [ ] add multi countries aggregations

**Comment by Bachibouzouk** [comment]
From live-discussion with @srhbrnds : the controls will be only for the se4all scenario (ticks the third point)

**Comment by Bachibouzouk** [comment]
From live-discussion with @srhbrnds : the minimum tier level will limited from 2 to 4 (ticks the fourth point)

**Comment by Bachibouzouk** [comment]
@srhbrnds - I've updated the checklist, feel free to edit it if you see some missing points :)
